### ISSUE TITLE
Bump windows cf CLI version to latest

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cf-smoke-tests-release#15]
The current blob is for cf CLI v8.3.0, while the latest cf CLI release is v8.5.0.

Perhaps we should update the pipeline to autobump this.
```[tasklist]
### Tasks
- [ ] https://github.com/cloudfoundry/cf-smoke-tests-release/pull/21
- [ ] https://github.com/cloudfoundry/runtime-ci/pull/255
- [ ] https://github.com/cloudfoundry/cf-smoke-tests-release/pull/22
```

**Comment by ctlong** [comment]
I looked into whether there was a package that we could use instead, and there isn't 😞. Just opened an issue in the cf-cli release to see if we can get one: https://github.com/cloudfoundry/bosh-package-cf-cli-release/issues/14.
